# Generated by Django 2.2.3 on 2019-10-27 00:37

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("platforma", "0002_auto_20191027_0030")]

    operations = [
        migrations.AlterField(
            model_name="assignmentcyclepair",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pairs",
                to="platforma.Assignment",
            ),
        )
    ]
