# Generated by Django 2.2.9 on 2020-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platforma", "0003_auto_20191027_0037"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=255)),
                ("currently_downloading", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("draft_posted", models.BooleanField(default=False)),
                ("deleted_old", models.BooleanField(default=False)),
                ("download_date", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="assignmentcyclepair", unique_together=None,
        ),
        migrations.RemoveField(model_name="assignmentcyclepair", name="assignment",),
        migrations.RemoveField(model_name="assignmentcyclepair", name="author",),
        migrations.RemoveField(model_name="assignmentcyclepair", name="reviewer",),
        migrations.AlterUniqueTogether(
            name="assignmentparticipant", unique_together=None,
        ),
        migrations.RemoveField(model_name="assignmentparticipant", name="assignment",),
        migrations.DeleteModel(name="Assignment",),
        migrations.DeleteModel(name="AssignmentCyclePair",),
        migrations.DeleteModel(name="AssignmentParticipant",),
    ]
