# Generated by Django 2.2.9 on 2020-02-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0004_auto_20200204_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='redownloaded',
            field=models.BooleanField(default=False),
        ),
    ]
