# Generated by Django 2.2.10 on 2020-08-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platforma", "0007_auto_20200207_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="deleted_by_uploader",
            field=models.BooleanField(default=False),
        ),
    ]
